apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: "${namespace}"
  labels:
    tenantid: "${namespace}"
type: Opaque
data:
  wmicadmin: __WMICADMIN_PASS__
  cloudadmin: __CLOUDADMIN_PASS__
  clusteradmin: __CLOUDADMIN_PASS__
  spmadmin: ${userPass}
