apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo
  namespace: "${tenantId}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: repo
        tenantid: "${tenantId}"
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: repo
        image: ${DOCKER_REPO}/cloud-deployment/cloud-repository:${TAG}
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        env:
        - name: DEBUG
          value: "1"
#        readinessProbe:
#          httpGet:
#            path: /status.html
#            port: 80
#          initialDelaySeconds: 15
#          periodSeconds: 30
#        livenessProbe:
#          httpGet:
#            path: /status.html
#            port: 80
#          initialDelaySeconds: 15
#          periodSeconds: 30
        resources:
          limits:
#            cpu: 0.4
            memory: 768Mi
          requests:
#            cpu: 0.2
            memory: 512Mi
        volumeMounts:
        - name: repo-data-volume
          mountPath: /opt/repo
        - name: repo-secret-volume
          mountPath: /opt/softwareag/common/auth/repo
          readOnly: true
      volumes:
      - name: repo-data-volume
        emptyDir: {}
      - name: repo-secret-volume
        secret:
          secretName: repo-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1724
        fsGroup: 1724
